# Generated by Django 6.0.5 on 2026-05-21 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0001_initial'),
        ('stadiums', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_score', models.PositiveIntegerField(blank=True, null=True)),
                ('away_score', models.PositiveIntegerField(blank=True, null=True)),
                ('penalty_home_score', models.PositiveIntegerField(blank=True, null=True)),
                ('penalty_away_score', models.PositiveIntegerField(blank=True, null=True)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('PLAYING', 'Playing'), ('HALF_TIME', 'Half Time'), ('EXTRA_TIME', 'Extra Time'), ('PENALTY_SHOOTOUT', 'Penalty Shootout'), ('FINISHED', 'Finished'), ('POSTPONED', 'Postponed'), ('TBC', 'TBC')], max_length=20)),
                ('leg', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('away_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='away_matches', to='teams.team')),
                ('competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='competitions.competitionphase')),
                ('home_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_matches', to='teams.team')),
                ('stadium', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stadiums.stadium')),
            ],
        ),
    ]
