# Generated by Django 6.0.5 on 2026-05-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_remove_match_date_match_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='leg',
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('PLAYING', 'Playing'), ('HALF_TIME', 'Half Time'), ('EXTRA_TIME', 'Extra Time'), ('PENALTY_SHOOTOUT', 'Penalty Shootout'), ('FINISHED', 'Finished'), ('POSTPONED', 'Postponed'), ('TBC', 'TBC'), ('CANCELLED', 'Cancelled'), ('SCHEDULED', 'Scheduled')], max_length=20),
        ),
    ]
