# Generated by Django 6.0.5 on 2026-05-27 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
        ('standings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standing',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.competition'),
        ),
    ]
