# Generated by Django 6.0.5 on 2026-05-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_remove_team_logo_url_team_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.FileField(blank=True, upload_to='team_logos'),
        ),
    ]
