# Generated by Django 6.0.5 on 2026-05-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='flag_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
