# Generated by Django 6.0.5 on 2026-05-21 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(blank=True, max_length=20)),
                ('format', models.CharField(choices=[('LEAGUE', 'League'), ('CUP', 'Cup'), ('LEAGUE_KNOCKOUT', 'League Knockout')], max_length=20)),
                ('start_year', models.PositiveIntegerField()),
                ('end_year', models.PositiveIntegerField()),
                ('logo_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='countries.country')),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('GROUP_STAGE', 'Group Stage'), ('KNOCKOUT_STAGE', 'Knockout Stage'), ('LEAGUE_STAGE', 'League Stage')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.competition')),
            ],
        ),
    ]
