# Generated by Django 6.0.5 on 2026-05-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionphase',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
